- name: using Handlers
  hosts: all
	tasks:
	  - name: insatll the package
		  yum:
			  name: httpd
				state: latest
		  notify:
		    - handl

		- name: print his
		  debug:
			   msg: Hello There

	handlers:
	  - name: handl
		  service:
			  name: httpd
				state: started
				enabled: yes
