- name: second playbook
  hosts: all
  tasks:
    - name: task1
      debug:
        msg: "Hello There"
      changed_when: true
      notify
        - handl

  handlers:
    - name: handl
      debug:
        msg: handler
