- name: Configure HTTPD
  hosts: all
  tasks:
  - name: install httpd
    yum:       
      name: httpd
      state: latest

  - name: Create index file
    copy:
      content: "Hi Sanofi"
      dest: /var/www/html/index.html
  
  - name: start HTTPD service
    service:
      name: httpd
      state: started

  - name: enable firewalld
    firewalld:
      service: http
      state: enabled
      permanent: yes
      immediate: yes
